from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QSizePolicy,
    QWidget)

import poster_rc

class Ui_tela_principal(object):
    def setupUi(self, tela_principal):
        if not tela_principal.objectName():
            tela_principal.setObjectName(u"tela_principal")
        tela_principal.resize(1087, 526)
        self.tela_inicial = QFrame(tela_principal)
        self.tela_inicial.setObjectName(u"tela_inicial")
        self.tela_inicial.setGeometry(QRect(20, 10, 1031, 501))
        self.tela_inicial.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.tela_inicial.setFrameShape(QFrame.Shape.StyledPanel)
        self.tela_inicial.setFrameShadow(QFrame.Shadow.Raised)
        self.inicial = QFrame(self.tela_inicial)
        self.inicial.setObjectName(u"inicial")
        self.inicial.setGeometry(QRect(0, 0, 1041, 61))
        self.inicial.setStyleSheet(u"background-color: rgb(34, 31, 31);")
        self.inicial.setFrameShape(QFrame.Shape.StyledPanel)
        self.inicial.setFrameShadow(QFrame.Shadow.Raised)
        self.txt_Cine_filme = QLabel(self.inicial)
        self.txt_Cine_filme.setObjectName(u"txt_Cine_filme")
        self.txt_Cine_filme.setGeometry(QRect(10, 10, 161, 41))
        self.txt_Cine_filme.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 900 22pt \"Segoe UI\";")
        self.txt_Filmes_Series = QLabel(self.inicial)
        self.txt_Filmes_Series.setObjectName(u"txt_Filmes_Series")
        self.txt_Filmes_Series.setGeometry(QRect(220, 20, 121, 21))
        self.txt_Filmes_Series.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.txt_Recomendacao_aleatoria = QLabel(self.inicial)
        self.txt_Recomendacao_aleatoria.setObjectName(u"txt_Recomendacao_aleatoria")
        self.txt_Recomendacao_aleatoria.setGeometry(QRect(350, 20, 211, 21))
        self.txt_Recomendacao_aleatoria.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.icon_perfil = QLabel(self.inicial)
        self.icon_perfil.setObjectName(u"icon_perfil")
        self.icon_perfil.setGeometry(QRect(980, 20, 27, 27))
        self.icon_perfil.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.icon_perfil.setPixmap(QPixmap(u":/icon/icon_perfil.png"))
        self.icon_perfil.setScaledContents(True)
        self.icon_perfil.raise_()
        self.txt_Cine_filme.raise_()
        self.txt_Filmes_Series.raise_()
        self.txt_Recomendacao_aleatoria.raise_()
        self.img_Star_wars = QLabel(self.tela_inicial)
        self.img_Star_wars.setObjectName(u"img_Star_wars")
        self.img_Star_wars.setGeometry(QRect(20, 140, 71, 121))
        self.img_Star_wars.setPixmap(QPixmap(u":/icon/star wars.webp"))
        self.img_Star_wars.setScaledContents(True)
        self.img_Whicked = QLabel(self.tela_inicial)
        self.img_Whicked.setObjectName(u"img_Whicked")
        self.img_Whicked.setGeometry(QRect(110, 140, 81, 121))
        self.img_Whicked.setPixmap(QPixmap(u":/icon/btn_img_wicked.png"))
        self.img_Whicked.setScaledContents(True)
        self.img_Flow = QLabel(self.tela_inicial)
        self.img_Flow.setObjectName(u"img_Flow")
        self.img_Flow.setGeometry(QRect(218, 140, 81, 121))
        self.img_Flow.setPixmap(QPixmap(u":/icon/flow.webp"))
        self.img_Flow.setScaledContents(True)
        self.img_Ainda_estou_aqui = QLabel(self.tela_inicial)
        self.img_Ainda_estou_aqui.setObjectName(u"img_Ainda_estou_aqui")
        self.img_Ainda_estou_aqui.setGeometry(QRect(320, 140, 81, 121))
        self.img_Ainda_estou_aqui.setPixmap(QPixmap(u":/icon/Ainda_Estou_Aqui.jpg"))
        self.img_Ainda_estou_aqui.setScaledContents(True)
        self.label_9 = QLabel(self.tela_inicial)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(420, 140, 81, 121))
        self.label_9.setPixmap(QPixmap(u":/icon/robo.jpg"))
        self.label_9.setScaledContents(True)
        self.img_Avengers = QLabel(self.tela_inicial)
        self.img_Avengers.setObjectName(u"img_Avengers")
        self.img_Avengers.setGeometry(QRect(520, 140, 81, 121))
        self.img_Avengers.setPixmap(QPixmap(u":/icon/avengers.jpg"))
        self.img_Avengers.setScaledContents(True)
        self.img_Diverdida_mente_2 = QLabel(self.tela_inicial)
        self.img_Diverdida_mente_2.setObjectName(u"img_Diverdida_mente_2")
        self.img_Diverdida_mente_2.setGeometry(QRect(620, 140, 81, 121))
        self.img_Diverdida_mente_2.setPixmap(QPixmap(u":/icon/disney.jpeg"))
        self.img_Diverdida_mente_2.setScaledContents(True)
        self.img_Jonh_Wick_3 = QLabel(self.tela_inicial)
        self.img_Jonh_Wick_3.setObjectName(u"img_Jonh_Wick_3")
        self.img_Jonh_Wick_3.setGeometry(QRect(720, 140, 91, 121))
        self.img_Jonh_Wick_3.setPixmap(QPixmap(u":/icon/Jonh wick.jpg"))
        self.img_Jonh_Wick_3.setScaledContents(True)
        self.img_Duna_parte_2 = QLabel(self.tela_inicial)
        self.img_Duna_parte_2.setObjectName(u"img_Duna_parte_2")
        self.img_Duna_parte_2.setGeometry(QRect(840, 140, 81, 131))
        self.img_Duna_parte_2.setPixmap(QPixmap(u":/icon/duna 2.webp"))
        self.img_Duna_parte_2.setScaledContents(True)
        self.img_One_Piece_2 = QLabel(self.tela_inicial)
        self.img_One_Piece_2.setObjectName(u"img_One_Piece_2")
        self.img_One_Piece_2.setGeometry(QRect(120, 310, 81, 141))
        self.img_One_Piece_2.setPixmap(QPixmap(u":/icon/one piece red.jpg"))
        self.img_One_Piece_2.setScaledContents(True)
        self.img_Solteiro_em_seul = QLabel(self.tela_inicial)
        self.img_Solteiro_em_seul.setObjectName(u"img_Solteiro_em_seul")
        self.img_Solteiro_em_seul.setGeometry(QRect(20, 310, 81, 141))
        self.img_Solteiro_em_seul.setPixmap(QPixmap(u":/icon/single in seul.jpg"))
        self.img_Solteiro_em_seul.setScaledContents(True)
        self.img_ghost_in_the_shell = QLabel(self.tela_inicial)
        self.img_ghost_in_the_shell.setObjectName(u"img_ghost_in_the_shell")
        self.img_ghost_in_the_shell.setGeometry(QRect(220, 310, 81, 141))
        self.img_ghost_in_the_shell.setPixmap(QPixmap(u":/icon/ghost in the shell.jpg"))
        self.img_ghost_in_the_shell.setScaledContents(True)
        self.img_Gladiador_2 = QLabel(self.tela_inicial)
        self.img_Gladiador_2.setObjectName(u"img_Gladiador_2")
        self.img_Gladiador_2.setGeometry(QRect(320, 310, 81, 141))
        self.img_Gladiador_2.setPixmap(QPixmap(u":/icon/Gladiador 2.webp"))
        self.img_Gladiador_2.setScaledContents(True)
        self.img_Senna = QLabel(self.tela_inicial)
        self.img_Senna.setObjectName(u"img_Senna")
        self.img_Senna.setGeometry(QRect(420, 310, 81, 141))
        self.img_Senna.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.img_Senna.setPixmap(QPixmap(u":/icon/sena.webp"))
        self.img_Senna.setScaledContents(True)
        self.img_Substancia = QLabel(self.tela_inicial)
        self.img_Substancia.setObjectName(u"img_Substancia")
        self.img_Substancia.setGeometry(QRect(520, 310, 91, 141))
        self.img_Substancia.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.img_Substancia.setPixmap(QPixmap(u":/icon/substancia.jpg"))
        self.img_Substancia.setScaledContents(True)
        self.img_Round_6 = QLabel(self.tela_inicial)
        self.img_Round_6.setObjectName(u"img_Round_6")
        self.img_Round_6.setGeometry(QRect(630, 310, 81, 141))
        self.img_Round_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.img_Round_6.setPixmap(QPixmap(u":/icon/round 6.jpg"))
        self.img_Round_6.setScaledContents(True)
        self.img_Pousando_no_amor = QLabel(self.tela_inicial)
        self.img_Pousando_no_amor.setObjectName(u"img_Pousando_no_amor")
        self.img_Pousando_no_amor.setGeometry(QRect(730, 310, 81, 141))
        self.img_Pousando_no_amor.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.img_Pousando_no_amor.setPixmap(QPixmap(u":/icon/pousando no amor.jpg"))
        self.img_Pousando_no_amor.setScaledContents(True)
        self.img_Shop_For_killers = QLabel(self.tela_inicial)
        self.img_Shop_For_killers.setObjectName(u"img_Shop_For_killers")
        self.img_Shop_For_killers.setGeometry(QRect(840, 310, 81, 141))
        self.img_Shop_For_killers.setPixmap(QPixmap(u":/icon/shop for killer.jpeg"))
        self.img_Shop_For_killers.setScaledContents(True)
        self.img_Duna_A_Profecia = QLabel(self.tela_inicial)
        self.img_Duna_A_Profecia.setObjectName(u"img_Duna_A_Profecia")
        self.img_Duna_A_Profecia.setGeometry(QRect(940, 310, 81, 141))
        self.img_Duna_A_Profecia.setPixmap(QPixmap(u":/icon/duna serie.jpg"))
        self.img_Duna_A_Profecia.setScaledContents(True)
        self.img_O_Problema_dos_tres_corpos = QLabel(self.tela_inicial)
        self.img_O_Problema_dos_tres_corpos.setObjectName(u"img_O_Problema_dos_tres_corpos")
        self.img_O_Problema_dos_tres_corpos.setGeometry(QRect(940, 140, 71, 131))
        self.img_O_Problema_dos_tres_corpos.setPixmap(QPixmap(u":/icon/O_Problema_dos_3_Corpos.webp"))
        self.img_O_Problema_dos_tres_corpos.setScaledContents(True)
        self.txt_Populares = QLabel(self.tela_inicial)
        self.txt_Populares.setObjectName(u"txt_Populares")
        self.txt_Populares.setGeometry(QRect(20, 100, 81, 16))
        self.txt_Populares.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe UI\";")

        self.retranslateUi(tela_principal)

        QMetaObject.connectSlotsByName(tela_principal)
    # setupUi

    def retranslateUi(self, tela_principal):
        tela_principal.setWindowTitle(QCoreApplication.translate("tela_principal", u"Form", None))
        self.txt_Cine_filme.setText(QCoreApplication.translate("tela_principal", u"CineFilmes", None))
        self.txt_Filmes_Series.setText(QCoreApplication.translate("tela_principal", u"Filmes e S\u00e9ries", None))
        self.txt_Recomendacao_aleatoria.setText(QCoreApplication.translate("tela_principal", u"Recomenda\u00e7\u00e3o aleat\u00f3ria", None))
        self.icon_perfil.setText("")
        self.img_Star_wars.setText("")
        self.img_Whicked.setText("")
        self.img_Flow.setText("")
        self.img_Ainda_estou_aqui.setText("")
        self.label_9.setText("")
        self.img_Avengers.setText("")
        self.img_Diverdida_mente_2.setText("")
        self.img_Jonh_Wick_3.setText("")
        self.img_Duna_parte_2.setText("")
        self.img_One_Piece_2.setText("")
        self.img_Solteiro_em_seul.setText("")
        self.img_ghost_in_the_shell.setText("")
        self.img_Gladiador_2.setText("")
        self.img_Senna.setText("")
        self.img_Substancia.setText("")
        self.img_Round_6.setText("")
        self.img_Pousando_no_amor.setText("")
        self.img_Shop_For_killers.setText("")
        self.img_Duna_A_Profecia.setText("")
        self.img_O_Problema_dos_tres_corpos.setText("")
        self.txt_Populares.setText(QCoreApplication.translate("tela_principal", u"Populares", None))
    # retranslateUi

import sys
from PySide6.QtWidgets import QApplication, QMainWindow
from tela_inicial import Ui_tela_principal

if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = QMainWindow()
    ui = Ui_tela_principal()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())

