from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QSizePolicy, QWidget)
import poster_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1028, 503)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.CineFilme = QFrame(self.centralwidget)
        self.CineFilme.setObjectName(u"CineFilme")
        self.CineFilme.setGeometry(QRect(140, 30, 771, 421))
        self.CineFilme.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.CineFilme.setFrameShape(QFrame.Shape.StyledPanel)
        self.CineFilme.setFrameShadow(QFrame.Shadow.Raised)
        self.txt_Cine_Filmes = QLabel(self.CineFilme)
        self.txt_Cine_Filmes.setObjectName(u"txt_Cine_Filmes")
        self.txt_Cine_Filmes.setGeometry(QRect(20, 0, 171, 41))
        self.txt_Cine_Filmes.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 900 20pt \"Segoe UI\";")
        self.txt_Filmes_e_Series = QLabel(self.CineFilme)
        self.txt_Filmes_e_Series.setObjectName(u"txt_Filmes_e_Series")
        self.txt_Filmes_e_Series.setGeometry(QRect(170, 10, 141, 21))
        self.txt_Filmes_e_Series.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 14pt \"Segoe UI\";")
        self.txt_Recomendacao_aleatoria = QLabel(self.CineFilme)
        self.txt_Recomendacao_aleatoria.setObjectName(u"txt_Recomendacao_aleatoria")
        self.txt_Recomendacao_aleatoria.setGeometry(QRect(320, 10, 221, 21))
        self.txt_Recomendacao_aleatoria.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 14pt \"Segoe UI\";")
        self.txt_Filmes_e_Series_Populares = QLabel(self.CineFilme)
        self.txt_Filmes_e_Series_Populares.setObjectName(u"txt_Filmes_e_Series_Populares")
        self.txt_Filmes_e_Series_Populares.setGeometry(QRect(30, 90, 231, 21))
        self.txt_Filmes_e_Series_Populares.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 14pt \"Segoe UI\";")
        self.img_Wicked = QLabel(self.CineFilme)
        self.img_Wicked.setObjectName(u"img_Wicked")
        self.img_Wicked.setGeometry(QRect(30, 120, 91, 121))
        self.img_Wicked.setPixmap(QPixmap(u":/icon 1/btn_img_wicked.png"))
        self.img_Wicked.setScaledContents(True)
        self.img_Ainda_estou_aqui = QLabel(self.CineFilme)
        self.img_Ainda_estou_aqui.setObjectName(u"img_Ainda_estou_aqui")
        self.img_Ainda_estou_aqui.setGeometry(QRect(140, 120, 81, 121))
        self.img_Ainda_estou_aqui.setPixmap(QPixmap(u":/icon 2/Ainda_Estou_Aqui.jpg"))
        self.img_Ainda_estou_aqui.setScaledContents(True)
        self.img_Substancia = QLabel(self.CineFilme)
        self.img_Substancia.setObjectName(u"img_Substancia")
        self.img_Substancia.setGeometry(QRect(250, 120, 81, 121))
        self.img_Substancia.setPixmap(QPixmap(u":/icon 3/substancia.jpg"))
        self.img_Substancia.setScaledContents(True)
        self.img_Round_6 = QLabel(self.CineFilme)
        self.img_Round_6.setObjectName(u"img_Round_6")
        self.img_Round_6.setGeometry(QRect(350, 120, 81, 121))
        self.img_Round_6.setPixmap(QPixmap(u":/icon 4/round 6.jpg"))
        self.img_Round_6.setScaledContents(True)
        self.img_Robo_Selvagem = QLabel(self.CineFilme)
        self.img_Robo_Selvagem.setObjectName(u"img_Robo_Selvagem")
        self.img_Robo_Selvagem.setGeometry(QRect(450, 120, 81, 121))
        self.img_Robo_Selvagem.setPixmap(QPixmap(u":/icon 5/robo.jpg"))
        self.img_Robo_Selvagem.setScaledContents(True)
        self.img_Flow = QLabel(self.CineFilme)
        self.img_Flow.setObjectName(u"img_Flow")
        self.img_Flow.setGeometry(QRect(550, 120, 81, 121))
        self.img_Flow.setPixmap(QPixmap(u":/icon 6/flow.webp"))
        self.img_Flow.setScaledContents(True)
        self.img_Gladiador_2 = QLabel(self.CineFilme)
        self.img_Gladiador_2.setObjectName(u"img_Gladiador_2")
        self.img_Gladiador_2.setGeometry(QRect(28, 270, 81, 121))
        self.img_Gladiador_2.setPixmap(QPixmap(u":/icon 7/Gladiador 2.webp"))
        self.img_Gladiador_2.setScaledContents(True)
        self.img_Jurado_2 = QLabel(self.CineFilme)
        self.img_Jurado_2.setObjectName(u"img_Jurado_2")
        self.img_Jurado_2.setGeometry(QRect(140, 270, 81, 121))
        self.img_Jurado_2.setPixmap(QPixmap(u":/icon 8/jurado n 2.webp"))
        self.img_Jurado_2.setScaledContents(True)
        self.img_Duna_parte_2 = QLabel(self.CineFilme)
        self.img_Duna_parte_2.setObjectName(u"img_Duna_parte_2")
        self.img_Duna_parte_2.setGeometry(QRect(250, 270, 81, 121))
        self.img_Duna_parte_2.setPixmap(QPixmap(u":/icon 9/duna 2.webp"))
        self.img_Duna_parte_2.setScaledContents(True)
        self.img_Diverdida_mente_2 = QLabel(self.CineFilme)
        self.img_Diverdida_mente_2.setObjectName(u"img_Diverdida_mente_2")
        self.img_Diverdida_mente_2.setGeometry(QRect(350, 270, 81, 121))
        self.img_Diverdida_mente_2.setPixmap(QPixmap(u":/icon 10/disney.jpeg"))
        self.img_Diverdida_mente_2.setScaledContents(True)
        self.img_Moana_2 = QLabel(self.CineFilme)
        self.img_Moana_2.setObjectName(u"img_Moana_2")
        self.img_Moana_2.setGeometry(QRect(450, 270, 81, 121))
        self.img_Moana_2.setPixmap(QPixmap(u":/icon 11/moana.jpg"))
        self.img_Moana_2.setScaledContents(True)
        self.img_Senna = QLabel(self.CineFilme)
        self.img_Senna.setObjectName(u"img_Senna")
        self.img_Senna.setGeometry(QRect(550, 270, 81, 121))
        self.img_Senna.setPixmap(QPixmap(u":/icon 12/sena.webp"))
        self.img_Senna.setScaledContents(True)
        self.img_Pousando_no_amor = QLabel(self.CineFilme)
        self.img_Pousando_no_amor.setObjectName(u"img_Pousando_no_amor")
        self.img_Pousando_no_amor.setGeometry(QRect(650, 120, 91, 121))
        self.img_Pousando_no_amor.setPixmap(QPixmap(u":/icon 13/pousando no amor.jpg"))
        self.img_Pousando_no_amor.setScaledContents(True)
        self.img_Shoop_for_killers = QLabel(self.CineFilme)
        self.img_Shoop_for_killers.setObjectName(u"img_Shoop_for_killers")
        self.img_Shoop_for_killers.setGeometry(QRect(660, 270, 81, 111))
        self.img_Shoop_for_killers.setPixmap(QPixmap(u":/icon 14/shop for killer.jpeg"))
        self.img_Shoop_for_killers.setScaledContents(True)
        self.icon_perfil = QLabel(self.CineFilme)
        self.icon_perfil.setObjectName(u"icon_perfil")
        self.icon_perfil.setGeometry(QRect(740, 10, 21, 21))
        self.icon_perfil.setPixmap(QPixmap(u":/icon 1/icon_perfil.png"))
        self.icon_perfil.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1028, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.txt_Cine_Filmes.setText(QCoreApplication.translate("MainWindow", u"CineFilme", None))
        self.txt_Filmes_e_Series.setText(QCoreApplication.translate("MainWindow", u"Filmes e S\u00e9ries", None))
        self.txt_Recomendacao_aleatoria.setText(QCoreApplication.translate("MainWindow", u"Recomenda\u00e7\u00e3o aleat\u00f3ria", None))
        self.txt_Filmes_e_Series_Populares.setText(QCoreApplication.translate("MainWindow", u"Filmes e s\u00e9ries Populares ", None))
        self.img_Wicked.setText("")
        self.img_Ainda_estou_aqui.setText("")
        self.img_Substancia.setText("")
        self.img_Round_6.setText("")
        self.img_Robo_Selvagem.setText("")
        self.img_Flow.setText("")
        self.img_Gladiador_2.setText("")
        self.img_Jurado_2.setText("")
        self.img_Duna_parte_2.setText("")
        self.img_Diverdida_mente_2.setText("")
        self.img_Moana_2.setText("")
        self.img_Senna.setText("")
        self.img_Pousando_no_amor.setText("")
        self.img_Shoop_for_killers.setText("")
        self.icon_perfil.setText("")
    # retranslateUi

import tela_inicial, sys
from tela_inicial import Ui_MainWindow
 
if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())                   
